function InputParametersAll = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  INPUTPARAMETERSALL = IMPORTFILE1(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  INPUTPARAMETERSALL = IMPORTFILE1(FILE, SHEET) reads from the
%  specified worksheet.
%
%  INPUTPARAMETERSALL = IMPORTFILE1(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  InputParametersAll = importfile1("C:\Users\alice\Desktop\2023_11_29_Model_PT_fO2\Input_Parameters_All.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Dec-2023 10:27:49

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 11];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Element", "AtomicMass", "Oxide_comp", "Weight", "ParametersdeltaG0", "Values", "Oxides_acttivity", "Margules"];
opts.VariableTypes = ["string", "double", "string", "double", "string", "double", "string", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Element", "Oxide_comp", "ParametersdeltaG0", "Oxides_acttivity"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Element", "Oxide_comp", "ParametersdeltaG0", "Oxides_acttivity"], "EmptyFieldRule", "auto");

% Import the data
InputParametersAll = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    InputParametersAll = [InputParametersAll; tb]; %#ok<AGROW>
end

end